# Form implementation generated from reading ui file 'administracion.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormAdministracion(object):
    def setupUi(self, FormAdministracion):
        FormAdministracion.setObjectName("FormAdministracion")
        FormAdministracion.resize(907, 790)#tamaño
        
        self.frameAdministracion = QtWidgets.QFrame(parent=FormAdministracion)
        self.frameAdministracion.setGeometry(QtCore.QRect(0, 0, 901, 791))#posicion
        self.frameAdministracion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameAdministracion.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameAdministracion.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameAdministracion.setObjectName("frameAdministracion")
        
        self.label_86 = QtWidgets.QLabel(parent=self.frameAdministracion)
        self.label_86.setGeometry(QtCore.QRect(290, 20, 211, 71))
        self.label_86.setObjectName("label_86")
        
        self.BotonNuevaEmpresa = QtWidgets.QPushButton(parent=self.frameAdministracion)
        self.BotonNuevaEmpresa.setGeometry(QtCore.QRect(100, 100, 101, 31))
        self.BotonNuevaEmpresa.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BotonNuevaEmpresa.setObjectName("BotonNuevaEmpresa")
        
        self.BotonNuevoAlmacen = QtWidgets.QPushButton(parent=self.frameAdministracion)
        self.BotonNuevoAlmacen.setGeometry(QtCore.QRect(590, 90, 91, 31))
        self.BotonNuevoAlmacen.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BotonNuevoAlmacen.setObjectName("BotonNuevoAlmacen")
        
        self.stackedWidget_7 = QtWidgets.QStackedWidget(parent=self.frameAdministracion)
        self.stackedWidget_7.setGeometry(QtCore.QRect(80, 170, 691, 451))
        self.stackedWidget_7.setObjectName("stackedWidget_7")
        
        self.NuevaEmpresa = QtWidgets.QWidget()
        self.NuevaEmpresa.setObjectName("NuevaEmpresa")
        self.frame_23 = QtWidgets.QFrame(parent=self.NuevaEmpresa)
        self.frame_23.setGeometry(QtCore.QRect(200, 60, 301, 351))
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.inputNombreEmpresa = QtWidgets.QLineEdit(parent=self.frame_23)
        self.inputNombreEmpresa.setGeometry(QtCore.QRect(160, 40, 113, 20))
        self.inputNombreEmpresa.setObjectName("inputNombreEmpresa")
        self.inputTelefonoEmpresa = QtWidgets.QLineEdit(parent=self.frame_23)
        self.inputTelefonoEmpresa.setGeometry(QtCore.QRect(160, 80, 113, 20))
        self.inputTelefonoEmpresa.setObjectName("inputTelefonoEmpresa")
        self.inputCorreoEmpresa = QtWidgets.QLineEdit(parent=self.frame_23)
        self.inputCorreoEmpresa.setGeometry(QtCore.QRect(160, 120, 113, 20))
        self.inputCorreoEmpresa.setObjectName("inputCorreoEmpresa")
        self.inputCuilEmpresa = QtWidgets.QLineEdit(parent=self.frame_23)
        self.inputCuilEmpresa.setGeometry(QtCore.QRect(160, 160, 113, 20))
        self.inputCuilEmpresa.setObjectName("inputCuilEmpresa")
        self.inputLogoEmpresa = QtWidgets.QLineEdit(parent=self.frame_23)
        self.inputLogoEmpresa.setGeometry(QtCore.QRect(160, 200, 113, 20))
        self.inputLogoEmpresa.setObjectName("inputLogoEmpresa")
        self.inputDireccionEmpresa = QtWidgets.QLineEdit(parent=self.frame_23)
        self.inputDireccionEmpresa.setGeometry(QtCore.QRect(160, 240, 113, 20))
        self.inputDireccionEmpresa.setObjectName("inputDireccionEmpresa")
        self.label_87 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_87.setGeometry(QtCore.QRect(60, 40, 47, 13))
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_88.setGeometry(QtCore.QRect(60, 80, 47, 13))
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_89.setGeometry(QtCore.QRect(60, 120, 47, 13))
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_90.setGeometry(QtCore.QRect(60, 160, 47, 13))
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_91.setGeometry(QtCore.QRect(60, 200, 47, 13))
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_92.setGeometry(QtCore.QRect(60, 240, 47, 13))
        self.label_92.setObjectName("label_92")
        self.BotonCrearAlmacen = QtWidgets.QPushButton(parent=self.frame_23)
        self.BotonCrearAlmacen.setGeometry(QtCore.QRect(110, 300, 75, 23))
        self.BotonCrearAlmacen.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BotonCrearAlmacen.setObjectName("BotonCrearAlmacen")
        self.stackedWidget_7.addWidget(self.NuevaEmpresa)                                  #Agrega el widget a la pila de widgets
        
        #imprimir pila de widgets en consola
        print(self.stackedWidget_7)
        
        
        self.NuevoAlmacen = QtWidgets.QWidget()
        self.NuevoAlmacen.setObjectName("NuevoAlmacen")
        self.frame_24 = QtWidgets.QFrame(parent=self.NuevoAlmacen)
        self.frame_24.setGeometry(QtCore.QRect(180, 30, 291, 351))
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.inputCapacidadAlmacen = QtWidgets.QLineEdit(parent=self.frame_24)
        self.inputCapacidadAlmacen.setGeometry(QtCore.QRect(150, 60, 113, 20))
        self.inputCapacidadAlmacen.setObjectName("inputCapacidadAlmacen")
        self.inputUsoAlmacen = QtWidgets.QLineEdit(parent=self.frame_24)
        self.inputUsoAlmacen.setGeometry(QtCore.QRect(150, 100, 113, 20))
        self.inputUsoAlmacen.setObjectName("inputUsoAlmacen")
        self.inputEmpresaAlmacen = QtWidgets.QLineEdit(parent=self.frame_24)
        self.inputEmpresaAlmacen.setGeometry(QtCore.QRect(150, 140, 113, 20))
        self.inputEmpresaAlmacen.setObjectName("inputEmpresaAlmacen")
        self.inputDireccionAlmacen = QtWidgets.QLineEdit(parent=self.frame_24)
        self.inputDireccionAlmacen.setGeometry(QtCore.QRect(150, 180, 113, 20))
        self.inputDireccionAlmacen.setObjectName("inputDireccionAlmacen")
        self.label_93 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_93.setGeometry(QtCore.QRect(60, 60, 61, 20))
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_94.setGeometry(QtCore.QRect(60, 100, 47, 13))
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_95.setGeometry(QtCore.QRect(60, 140, 47, 13))
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_96.setGeometry(QtCore.QRect(60, 180, 47, 13))
        self.label_96.setObjectName("label_96")
        self.botonCrearAlmacen = QtWidgets.QPushButton(parent=self.frame_24)
        self.botonCrearAlmacen.setGeometry(QtCore.QRect(100, 250, 75, 23))
        self.botonCrearAlmacen.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.botonCrearAlmacen.setObjectName("botonCrearAlmacen")
        self.stackedWidget_7.addWidget(self.NuevoAlmacen)                                                 #Agrega el widget a la pila de widgets
        
        self.Bienvenidos = QtWidgets.QWidget()
        self.Bienvenidos.setObjectName("Bienvenidos")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.Bienvenidos)
        self.textBrowser.setGeometry(QtCore.QRect(70, 40, 521, 371))
        self.textBrowser.setObjectName("textBrowser")
        self.stackedWidget_7.addWidget(self.Bienvenidos)                                                  #Agrega el widget a la pila de widgets

        self.retranslateUi(FormAdministracion)
        self.stackedWidget_7.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(FormAdministracion)
        
        #imprimir pila de widgets en consola
        print(self.stackedWidget_7)
        
        #conectar botones a funciones
        self.BotonNuevaEmpresa.clicked.connect(self.mostrarNuevaEmpresa)
        self.BotonNuevoAlmacen.clicked.connect(self.mostrarNuevoAlmacen)
        

    def retranslateUi(self, FormAdministracion):
        _translate = QtCore.QCoreApplication.translate
        FormAdministracion.setWindowTitle(_translate("FormAdministracion", "Form"))
        self.label_86.setText(_translate("FormAdministracion", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">ADMINISTRACION</span></p></body></html>"))
        self.BotonNuevaEmpresa.setText(_translate("FormAdministracion", "Nueva empresa"))
        self.BotonNuevoAlmacen.setText(_translate("FormAdministracion", "Nuevo almacen"))
        self.label_87.setText(_translate("FormAdministracion", "Nombre"))
        self.label_88.setText(_translate("FormAdministracion", "Telefono"))
        self.label_89.setText(_translate("FormAdministracion", "Correo"))
        self.label_90.setText(_translate("FormAdministracion", "Cuil"))
        self.label_91.setText(_translate("FormAdministracion", "Logo"))
        self.label_92.setText(_translate("FormAdministracion", "Direccion"))
        self.BotonCrearAlmacen.setText(_translate("FormAdministracion", "Crear"))
        self.label_93.setText(_translate("FormAdministracion", "Capacidad"))
        self.label_94.setText(_translate("FormAdministracion", "Uso"))
        self.label_95.setText(_translate("FormAdministracion", "Empresa"))
        self.label_96.setText(_translate("FormAdministracion", "Direccion"))
        self.botonCrearAlmacen.setText(_translate("FormAdministracion", "Crear"))
        self.textBrowser.setHtml(_translate("FormAdministracion", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                       <span style=\" font-size:18pt;\">BIENVENIDOS AL GESTOR</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">    </span><span style=\" font-size:10pt;\">Para comenzar a utulizar este gestor de inventario debera crear una nueva empresa al igual que un nuevo almacen; una ves realziadas estas acciones podra realziar las sigueintes: Registrar usuarios con roles </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">                 Registrar la ventas                                     Registrar las compras        </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">                                 Registrar Devoluciones<br />                 Acceder o modificar todos los datos previamente mencionados<br />                                 Acceder a los elementos de cada almancen y su capasidad</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">                 Podra generar facturas por cada venta y acceder a estas.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Entre otras cosas, este programa se encuentra en constante evolucion y se iran agregando nuevas funcionalidades. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Esperamos que lo disfrute.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">ATTE grupo UTNMMXXIII</span></p></body></html>"))

    def mostrarNuevaEmpresa(self):
        self.stackedWidget_7.setCurrentIndex(0)
    def mostrarNuevoAlmacen(self):
        self.stackedWidget_7.setCurrentIndex(1)
    def mostrarBienvenidos(self):
        self.stackedWidget_7.setCurrentIndex(2)