# Form implementation generated from reading ui file 'almacen.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormAlmacen(object):
    def setupUi(self, FormAlmacen):
        FormAlmacen.setObjectName("FormAlmacen")
        FormAlmacen.resize(907, 790)
        
        self.frameAlmacen = QtWidgets.QFrame(parent=FormAlmacen)
        self.frameAlmacen.setGeometry(QtCore.QRect(0, 0, 901, 791))
        self.frameAlmacen.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameAlmacen.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameAlmacen.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameAlmacen.setObjectName("frameAlmacen")
        
        self.ButtonBuscarALm = QtWidgets.QPushButton(parent=self.frameAlmacen)
        self.ButtonBuscarALm.setGeometry(QtCore.QRect(650, 100, 91, 31))
        self.ButtonBuscarALm.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.ButtonBuscarALm.setObjectName("ButtonBuscarALm")
        
        self.BotonNuevoArt = QtWidgets.QPushButton(parent=self.frameAlmacen)
        self.BotonNuevoArt.setGeometry(QtCore.QRect(770, 100, 91, 31))
        self.BotonNuevoArt.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.BotonNuevoArt.setObjectName("BotonNuevoArt")
        
        self.stackedWidget_6 = QtWidgets.QStackedWidget(parent=self.frameAlmacen)
        self.stackedWidget_6.setGeometry(QtCore.QRect(230, 250, 511, 461))
        self.stackedWidget_6.setObjectName("stackedWidget_6")
        
        self.BuscarAlmacen = QtWidgets.QWidget()
        self.BuscarAlmacen.setObjectName("BuscarAlmacen")
        
        self.TablaAlmacen = QtWidgets.QTableWidget(parent=self.BuscarAlmacen)
        self.TablaAlmacen.setGeometry(QtCore.QRect(0, 0, 511, 461))
        self.TablaAlmacen.setObjectName("TablaAlmacen")
        self.TablaAlmacen.setColumnCount(5)
        self.TablaAlmacen.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAlmacen.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAlmacen.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAlmacen.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAlmacen.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAlmacen.setHorizontalHeaderItem(4, item)
        self.stackedWidget_6.addWidget(self.BuscarAlmacen)                          #add widget
        
        self.NuevoArticulo = QtWidgets.QWidget()
        self.NuevoArticulo.setObjectName("NuevoArticulo")
        
        self.CreacionArticulo = QtWidgets.QFrame(parent=self.NuevoArticulo)
        self.CreacionArticulo.setGeometry(QtCore.QRect(40, 40, 411, 311))
        self.CreacionArticulo.setStyleSheet("border-color: rgb(6, 6, 6);")
        self.CreacionArticulo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.CreacionArticulo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.CreacionArticulo.setObjectName("CreacionArticulo")
        self.AltoArticulo = QtWidgets.QLineEdit(parent=self.CreacionArticulo)
        self.AltoArticulo.setGeometry(QtCore.QRect(230, 30, 113, 20))
        self.AltoArticulo.setObjectName("AltoArticulo")
        self.AnchoArticulo = QtWidgets.QLineEdit(parent=self.CreacionArticulo)
        self.AnchoArticulo.setGeometry(QtCore.QRect(230, 70, 113, 20))
        self.AnchoArticulo.setObjectName("AnchoArticulo")
        self.PesoArticulo = QtWidgets.QLineEdit(parent=self.CreacionArticulo)
        self.PesoArticulo.setGeometry(QtCore.QRect(230, 110, 113, 20))
        self.PesoArticulo.setObjectName("PesoArticulo")
        self.PrecioArticulo = QtWidgets.QLineEdit(parent=self.CreacionArticulo)
        self.PrecioArticulo.setGeometry(QtCore.QRect(230, 150, 113, 20))
        self.PrecioArticulo.setObjectName("PrecioArticulo")
        
        self.label_61 = QtWidgets.QLabel(parent=self.CreacionArticulo)
        self.label_61.setGeometry(QtCore.QRect(90, 30, 47, 13))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(parent=self.CreacionArticulo)
        self.label_62.setGeometry(QtCore.QRect(90, 70, 47, 13))
        self.label_62.setObjectName("label_62")
        self.label_64 = QtWidgets.QLabel(parent=self.CreacionArticulo)
        self.label_64.setGeometry(QtCore.QRect(90, 110, 51, 20))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(parent=self.CreacionArticulo)
        self.label_65.setGeometry(QtCore.QRect(90, 150, 101, 20))
        self.label_65.setObjectName("label_65")
        
        self.EnviarCrearArt = QtWidgets.QPushButton(parent=self.CreacionArticulo)
        self.EnviarCrearArt.setGeometry(QtCore.QRect(150, 230, 101, 41))
        self.EnviarCrearArt.setStyleSheet("\n"
"background-color: rgb(85, 255, 127);")
        self.EnviarCrearArt.setObjectName("EnviarCrearArt")
        self.stackedWidget_6.addWidget(self.NuevoArticulo)                              #add widget
        
        
        self.ModificarArticulo = QtWidgets.QWidget()
        self.ModificarArticulo.setObjectName("ModificarArticulo")
        self.stackedWidget_6.addWidget(self.ModificarArticulo)                          #add widget
        
        self.BucarAlmacen = QtWidgets.QLineEdit(parent=self.frameAlmacen)
        self.BucarAlmacen.setGeometry(QtCore.QRect(230, 100, 421, 31))
        self.BucarAlmacen.setObjectName("BucarAlmacen")
        self.label_84 = QtWidgets.QLabel(parent=self.frameAlmacen)
        self.label_84.setGeometry(QtCore.QRect(50, 90, 151, 41))
        self.label_84.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_84.setObjectName("label_84")
        self.CapacidadCargaALm = QtWidgets.QProgressBar(parent=self.frameAlmacen)
        self.CapacidadCargaALm.setGeometry(QtCore.QRect(490, 220, 261, 23))
        self.CapacidadCargaALm.setProperty("value", 24)
        self.CapacidadCargaALm.setObjectName("CapacidadCargaALm")
        self.label_85 = QtWidgets.QLabel(parent=self.frameAlmacen)
        self.label_85.setGeometry(QtCore.QRect(370, 220, 91, 20))
        self.label_85.setObjectName("label_85")

        self.retranslateUi(FormAlmacen)
        self.stackedWidget_6.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(FormAlmacen)
        
        #conectar botones a funciones
        self.ButtonBuscarALm.clicked.connect(self.mostrarBuscar)
        self.BotonNuevoArt.clicked.connect(self.mostrarNuevo)
        

    def retranslateUi(self, FormAlmacen):
        _translate = QtCore.QCoreApplication.translate
        FormAlmacen.setWindowTitle(_translate("FormAlmacen", "Form"))
        self.ButtonBuscarALm.setText(_translate("FormAlmacen", "Buscar "))
        self.BotonNuevoArt.setText(_translate("FormAlmacen", "Nuevo articulo"))
        item = self.TablaAlmacen.horizontalHeaderItem(0)
        item.setText(_translate("FormAlmacen", "id"))
        item = self.TablaAlmacen.horizontalHeaderItem(1)
        item.setText(_translate("FormAlmacen", "Producto"))
        item = self.TablaAlmacen.horizontalHeaderItem(2)
        item.setText(_translate("FormAlmacen", "Cantidad"))
        item = self.TablaAlmacen.horizontalHeaderItem(3)
        item.setText(_translate("FormAlmacen", "Tipo"))
        item = self.TablaAlmacen.horizontalHeaderItem(4)
        item.setText(_translate("FormAlmacen", "Volumen "))
        self.label_61.setText(_translate("FormAlmacen", "Alto"))
        self.label_62.setText(_translate("FormAlmacen", "Ancho"))
        self.label_64.setText(_translate("FormAlmacen", "Peso"))
        self.label_65.setText(_translate("FormAlmacen", "Precio"))
        self.EnviarCrearArt.setText(_translate("FormAlmacen", "Crear"))
        self.label_84.setText(_translate("FormAlmacen", "ALMACEN"))
        self.label_85.setText(_translate("FormAlmacen", "Capacidad usada"))

    #metodos stackwidget
    def mostrarBuscar(self):
        self.stackedWidget_6.setCurrentIndex(0)
    def mostrarNuevo(self):
        self.stackedWidget_6.setCurrentIndex(1)
    