from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormVentas(object):
    def setupUi(self, FormVentas):
        FormVentas.setObjectName("FormVentas")
        FormVentas.resize(900, 791)
        self.frameVentas = QtWidgets.QFrame(parent=FormVentas)
        self.frameVentas.setGeometry(QtCore.QRect(0, 0, 901, 791))
        self.frameVentas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameVentas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameVentas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameVentas.setObjectName("frameVentas")
        self.BotonBuscarVen = QtWidgets.QPushButton(parent=self.frameVentas)
        self.BotonBuscarVen.setGeometry(QtCore.QRect(560, 100, 91, 31))
        self.BotonBuscarVen.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.BotonBuscarVen.setObjectName("BotonBuscarVen")
        self.BotonNuevaVen = QtWidgets.QPushButton(parent=self.frameVentas)
        self.BotonNuevaVen.setGeometry(QtCore.QRect(770, 100, 91, 31))
        self.BotonNuevaVen.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.BotonNuevaVen.setObjectName("BotonNuevaVen")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(parent=self.frameVentas)
        self.stackedWidget_3.setGeometry(QtCore.QRect(50, 170, 811, 591))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.BuscarVentas = QtWidgets.QWidget()
        self.BuscarVentas.setObjectName("BuscarVentas")
        self.frame_8 = QtWidgets.QFrame(parent=self.BuscarVentas)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 811, 591))
        self.frame_8.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.tablaVentas = QtWidgets.QTableWidget(parent=self.frame_8)
        self.tablaVentas.setGeometry(QtCore.QRect(0, 0, 811, 591))
        self.tablaVentas.setObjectName("tablaVentas")
        self.tablaVentas.setColumnCount(8)
        self.tablaVentas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaVentas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaVentas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaVentas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaVentas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaVentas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaVentas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaVentas.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaVentas.setHorizontalHeaderItem(7, item)
        self.stackedWidget_3.addWidget(self.BuscarVentas)
        self.NuevaVenta_2 = QtWidgets.QWidget()
        self.NuevaVenta_2.setObjectName("NuevaVenta_2")
        self.frame_9 = QtWidgets.QFrame(parent=self.NuevaVenta_2)
        self.frame_9.setGeometry(QtCore.QRect(170, 40, 411, 531))
        self.frame_9.setStyleSheet("border-color: rgb(6, 6, 6);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.inputFechaven = QtWidgets.QLineEdit(parent=self.frame_9)
        self.inputFechaven.setGeometry(QtCore.QRect(230, 30, 113, 20))
        self.inputFechaven.setObjectName("inputFechaven")
        self.inputUsuarioVen = QtWidgets.QLineEdit(parent=self.frame_9)
        self.inputUsuarioVen.setGeometry(QtCore.QRect(230, 70, 113, 20))
        self.inputUsuarioVen.setObjectName("inputUsuarioVen")
        self.InputEnvioVem = QtWidgets.QLineEdit(parent=self.frame_9)
        self.InputEnvioVem.setGeometry(QtCore.QRect(230, 110, 113, 20))
        self.InputEnvioVem.setObjectName("InputEnvioVem")
        self.inputArticulo = QtWidgets.QLineEdit(parent=self.frame_9)
        self.inputArticulo.setGeometry(QtCore.QRect(230, 150, 113, 20))
        self.inputArticulo.setObjectName("inputArticulo")
        self.inputTipoVen = QtWidgets.QLineEdit(parent=self.frame_9)
        self.inputTipoVen.setGeometry(QtCore.QRect(230, 260, 113, 20))
        self.inputTipoVen.setObjectName("inputTipoVen")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_14.setGeometry(QtCore.QRect(90, 30, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_15.setGeometry(QtCore.QRect(90, 70, 47, 13))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_16.setGeometry(QtCore.QRect(90, 110, 47, 13))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_17.setGeometry(QtCore.QRect(90, 150, 51, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_18.setGeometry(QtCore.QRect(180, 220, 101, 20))
        self.label_18.setObjectName("label_18")
        self.botonCrearVen = QtWidgets.QPushButton(parent=self.frame_9)
        self.botonCrearVen.setGeometry(QtCore.QRect(150, 410, 101, 41))
        self.botonCrearVen.setStyleSheet("\n"
"background-color: rgb(85, 255, 127);")
        self.botonCrearVen.setObjectName("botonCrearVen")
        self.InputCuotasVen = QtWidgets.QLineEdit(parent=self.frame_9)
        self.InputCuotasVen.setGeometry(QtCore.QRect(230, 300, 113, 20))
        self.InputCuotasVen.setObjectName("InputCuotasVen")
        self.inputOrigenVen = QtWidgets.QLineEdit(parent=self.frame_9)
        self.inputOrigenVen.setGeometry(QtCore.QRect(230, 340, 113, 20))
        self.inputOrigenVen.setObjectName("inputOrigenVen")
        self.label_50 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_50.setGeometry(QtCore.QRect(90, 260, 51, 20))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_51.setGeometry(QtCore.QRect(90, 300, 51, 20))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_52.setGeometry(QtCore.QRect(90, 340, 51, 20))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(parent=self.NuevaVenta_2)
        self.label_53.setGeometry(QtCore.QRect(90, 110, 71, 16))
        self.label_53.setObjectName("label_53")
        self.stackedWidget_3.addWidget(self.NuevaVenta_2)
        self.ModificaVenta = QtWidgets.QWidget()
        self.ModificaVenta.setObjectName("ModificaVenta")
        self.frame_10 = QtWidgets.QFrame(parent=self.ModificaVenta)
        self.frame_10.setGeometry(QtCore.QRect(140, 40, 411, 531))
        self.frame_10.setStyleSheet("border-color: rgb(6, 6, 6);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.inputFechaModVen = QtWidgets.QLineEdit(parent=self.frame_10)
        self.inputFechaModVen.setGeometry(QtCore.QRect(230, 30, 113, 20))
        self.inputFechaModVen.setObjectName("inputFechaModVen")
        self.inputUsuarioModVen = QtWidgets.QLineEdit(parent=self.frame_10)
        self.inputUsuarioModVen.setGeometry(QtCore.QRect(230, 70, 113, 20))
        self.inputUsuarioModVen.setObjectName("inputUsuarioModVen")
        self.inputEnvioModVen = QtWidgets.QLineEdit(parent=self.frame_10)
        self.inputEnvioModVen.setGeometry(QtCore.QRect(230, 110, 113, 20))
        self.inputEnvioModVen.setObjectName("inputEnvioModVen")
        self.inputArticuloModVen = QtWidgets.QLineEdit(parent=self.frame_10)
        self.inputArticuloModVen.setGeometry(QtCore.QRect(230, 150, 113, 20))
        self.inputArticuloModVen.setObjectName("inputArticuloModVen")
        self.inputPagoTipoModVen = QtWidgets.QLineEdit(parent=self.frame_10)
        self.inputPagoTipoModVen.setGeometry(QtCore.QRect(230, 260, 113, 20))
        self.inputPagoTipoModVen.setObjectName("inputPagoTipoModVen")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_19.setGeometry(QtCore.QRect(90, 30, 47, 13))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_20.setGeometry(QtCore.QRect(90, 70, 47, 13))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_21.setGeometry(QtCore.QRect(90, 110, 47, 13))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_22.setGeometry(QtCore.QRect(90, 150, 51, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_23.setGeometry(QtCore.QRect(180, 220, 101, 20))
        self.label_23.setObjectName("label_23")
        self.BotonCrearModVen = QtWidgets.QPushButton(parent=self.frame_10)
        self.BotonCrearModVen.setGeometry(QtCore.QRect(150, 410, 101, 41))
        self.BotonCrearModVen.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.BotonCrearModVen.setObjectName("BotonCrearModVen")
        self.inputPagoCuotasModVen = QtWidgets.QLineEdit(parent=self.frame_10)
        self.inputPagoCuotasModVen.setGeometry(QtCore.QRect(230, 300, 113, 20))
        self.inputPagoCuotasModVen.setObjectName("inputPagoCuotasModVen")
        self.inputPagoOrigenModVen = QtWidgets.QLineEdit(parent=self.frame_10)
        self.inputPagoOrigenModVen.setGeometry(QtCore.QRect(230, 340, 113, 20))
        self.inputPagoOrigenModVen.setObjectName("inputPagoOrigenModVen")
        self.label_54 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_54.setGeometry(QtCore.QRect(90, 260, 51, 20))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_55.setGeometry(QtCore.QRect(90, 300, 51, 20))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_56.setGeometry(QtCore.QRect(90, 340, 51, 20))
        self.label_56.setObjectName("label_56")
        self.stackedWidget_3.addWidget(self.ModificaVenta)
        self.inputbuscarVen = QtWidgets.QLineEdit(parent=self.frameVentas)
        self.inputbuscarVen.setGeometry(QtCore.QRect(190, 100, 371, 31))
        self.inputbuscarVen.setObjectName("inputbuscarVen")
        self.label_24 = QtWidgets.QLabel(parent=self.frameVentas)
        self.label_24.setGeometry(QtCore.QRect(50, 90, 101, 41))
        self.label_24.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")

        self.retranslateUi(FormVentas)
        self.stackedWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormVentas)
        
        #botones a funciones
        self.BotonBuscarVen.clicked.connect(self.mostrarVentas)
        self.BotonNuevaVen.clicked.connect(self.mostrarNuevaVenta)
        

    def retranslateUi(self, FormVentas):
        _translate = QtCore.QCoreApplication.translate
        FormVentas.setWindowTitle(_translate("FormVentas", "Form"))
        self.BotonBuscarVen.setText(_translate("FormVentas", "Buscar ventas"))
        self.BotonNuevaVen.setText(_translate("FormVentas", "Nueva venta"))
        item = self.tablaVentas.horizontalHeaderItem(0)
        item.setText(_translate("FormVentas", "id"))
        item = self.tablaVentas.horizontalHeaderItem(1)
        item.setText(_translate("FormVentas", "Fecha"))
        item = self.tablaVentas.horizontalHeaderItem(2)
        item.setText(_translate("FormVentas", "Usuario"))
        item = self.tablaVentas.horizontalHeaderItem(3)
        item.setText(_translate("FormVentas", "Envio"))
        item = self.tablaVentas.horizontalHeaderItem(4)
        item.setText(_translate("FormVentas", "Articulo"))
        item = self.tablaVentas.horizontalHeaderItem(5)
        item.setText(_translate("FormVentas", "Pago"))
        item = self.tablaVentas.horizontalHeaderItem(6)
        item.setText(_translate("FormVentas", "Actualizar"))
        item = self.tablaVentas.horizontalHeaderItem(7)
        item.setText(_translate("FormVentas", "Borrar"))
        self.label_14.setText(_translate("FormVentas", "Fecha"))
        self.label_15.setText(_translate("FormVentas", "Usuario"))
        self.label_16.setText(_translate("FormVentas", "Envio"))
        self.label_17.setText(_translate("FormVentas", "Articulo"))
        self.label_18.setText(_translate("FormVentas", "Pago"))
        self.botonCrearVen.setText(_translate("FormVentas", "Crear"))
        self.label_50.setText(_translate("FormVentas", "Tipo"))
        self.label_51.setText(_translate("FormVentas", "Cuotas"))
        self.label_52.setText(_translate("FormVentas", "Origen"))
        self.label_53.setText(_translate("FormVentas", "probar selec"))
        self.label_19.setText(_translate("FormVentas", "Fecha"))
        self.label_20.setText(_translate("FormVentas", "Usuario"))
        self.label_21.setText(_translate("FormVentas", "Envio"))
        self.label_22.setText(_translate("FormVentas", "Articulo"))
        self.label_23.setText(_translate("FormVentas", "Pago"))
        self.BotonCrearModVen.setText(_translate("FormVentas", "Modificar"))
        self.label_54.setText(_translate("FormVentas", "Tipo"))
        self.label_55.setText(_translate("FormVentas", "Cuotas"))
        self.label_56.setText(_translate("FormVentas", "Origen"))
        self.label_24.setText(_translate("FormVentas", "VENTAS"))

    #funcion stackWidget
    def mostrarVentas(self):
        self.stackedWidget_3.setCurrentIndex(0)
        
    def mostrarNuevaVenta(self):
        self.stackedWidget_3.setCurrentIndex(1)